### ISSUE TITLE
Not compatible with donnemartin/gitsome

### ISSUE THREAD

**Issue by leoj3n** [chauncey-garrett/zsh-prompt-garrett#10] opened 2016-07-30 14:26 UTC
Try using this prompt with https://github.com/donnemartin/gitsome

Unfortunately it breaks the xonsh shell invoked by `gitsome`:

```
┌─( ~/.homesick/repos/prezto ⬆  master M e434b0a )──────────────────────────────( node:6.2.2 @3n )─┐
└─❱❱❱ gitsome                                                                         +5647 9:25 ❰─┘
Version: 0.6.0
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'prompt_garrett_color_prompt'
${prompt_garrett_altchar_enable}${prompt_garrett_color_prompt}${prompt_garrett_lower_left_corner}${ed
itor_info[keymap]}exit


┌─( ~/.homesick/repos/prezto ⬆  master M e434b0a )──────────────────────────────( node:6.2.2 @3n )─┐
└─❱❱❱                                                                                 +5647 9:25 ❰─┘
```

Any idea why?

**Comment by chauncey-garrett** [comment] 2016-09-19 03:41
I have no experience with `xonsh` so I can't be sure but I do know a [`KeyError`](https://docs.python.org/3/library/exceptions.html#KeyError) here means that `prompt_garrett_color_prompt` doesn't exist . I tried instantiating both `gitsome` and `xonsh` and found similar errors (but with different vars/functions from my prompt). I'm not sure why it's carrying over into `xonsh` though. May be best to take this upstream and report back? This may/may not help:

https://github.com/xonsh/xonsh/issues/1136

Also, if I run `env -i /usr/local/bin/xonsh`, I get a similar error:

```
Version: 0.6.0
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'HOME'
{BOLD_RED}{user} {BOLD_WHITE}at {BOLD_RED}{hostname} {BOLD_WHITE}in {BOLD_GREEN}{cw
${NO_COLOR} exit
```

Seeing a similar error here tells me that this issue is related to unknown environment variables.

What I do know is that the `PROMPT` environment variable should NOT carry over into `xonsh` (see [NOTE](http://xon.sh/tutorial.html#customizing-the-prompt)) so I think you're running into an upstream bug. You can verify this by setting `PROMPT` once you're using `xonsh`:

```
$ xonsh
Version: 0.6.0
xonsh: For full traceback set: $XONSH_SHOW_TRACEBACK = True
KeyError: 'prompt_garrett_lower_left_corner'
${prompt_garrett_altchar_enable}${prompt_garrett_color_prompt}${prompt_garrett_lowe
r_left_corner}${editor_info[keymap]}$PROMPT = '{user}@{hostname}:{cwd} > '
username@macbook:~ >
```

Closing for now since I believe the issue is not related to the prompt, but please do report back what you find and we can reopen if necessary.

**Closed as completed by chauncey-garrett** 2016-09-19 03:41 UTC

**Comment by leoj3n** [comment] 2016-09-20 12:40
Thanks for taking the time to investigate.
